### ISSUE TITLE
the comment on the website

### ISSUE THREAD

**Issue by artemD7** [AnastasiiaMamaeva/anastasiiamamaeva.github.io#2]
Hi Anastasia,

You have a wonderfull website! If you want, you can add there the link to the institution and to Gabor's web page as it was stated in the [Assignment day 1 recomendations](https://github.com/szabgab/wis-python-course-2024-11) :
"Create a nice page based on GitHub pages. Include information about yourself, your studies, your hobbies. Link to the institution and to my home page https://szabgab.com/ ."

@liroh99

**Comment by AnastasiiaMamaeva** [comment]
Oh, I misunderstood that I need to put this link on my site, I thought it was just a link for our reference :)
Thank you!

@liroh99

**Comment by artemD7** [comment]
Ok. Great! 😄
